// External test package (docs_test): the pin check imports both docs and
// internal/docs/gen/gencore, and gencore imports docs — an in-package
// (package docs) test would close that into an illegal import cycle. The
// external package sees only the exported API, which is sufficient here.
package docs_test

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/mjmorales/funpack/mcp/internal/docs"
	"github.com/mjmorales/funpack/mcp/internal/docs/gen/gencore"
)

// Committed corpus layout, relative to the package directory the tests run in
// (`go test` sets cwd to internal/docs). These mirror the unexported docs.go
// constants; the external test package cannot see those, and the filesystem
// layout is a stable contract.
const (
	corpusDirRel    = "corpus"
	manifestPathRel = "manifest.json"
)

// moduleRoot returns the mcp/ module root from the test's cwd. `go test` runs a
// package's tests with cwd set to the package directory (internal/docs), so the
// module root is two levels up.
func moduleRoot(t *testing.T) string {
	t.Helper()
	wd, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	return filepath.Clean(filepath.Join(wd, "..", ".."))
}

// regenOrSkip resolves the generator roots and regenerates the corpus in memory.
// When the funpack-spec sources are unavailable (no FUNPACK_SPEC_DIR and no
// sibling checkout) it t.Skips, keeping the pin test hermetic in environments
// without the spec — drift can only be asserted where the sources exist.
func regenOrSkip(t *testing.T) gencore.Result {
	t.Helper()
	r, err := gencore.ResolveRoots(moduleRoot(t))
	if err != nil {
		t.Skipf("funpack-spec sources unavailable, skipping corpus pin check: %v", err)
	}
	res, err := gencore.Generate(r)
	if err != nil {
		t.Fatalf("regenerate corpus: %v", err)
	}
	return res
}

// readCommitted reads a committed corpus artifact (corpus/<name> or
// manifest.json) from the package directory the test runs in.
func readCommitted(t *testing.T, rel string) []byte {
	t.Helper()
	b, err := os.ReadFile(rel)
	if err != nil {
		t.Fatalf("read committed %s: %v", rel, err)
	}
	return b
}

// TestCorpusPinShardsByteMatch is the corpus pin gate: it regenerates each
// per-kind shard through the same gencore extractor that built the committed
// corpus and asserts the regenerated bytes equal the committed corpus/*.json
// byte-for-byte. A drift — spec edit, engine signature change, plugin skill
// rewrite, or a stale checkout — fails the build here, forcing `task docs-regen`
// + recommit. Skips cleanly when the spec sources are absent.
func TestCorpusPinShardsByteMatch(t *testing.T) {
	res := regenOrSkip(t)

	shards := []struct {
		name     string
		sections []docs.Section
	}{
		{"spec.json", res.Spec},
		{"engine.json", res.Engine},
		{"plugin.json", res.Plugin},
	}
	for _, sh := range shards {
		got, err := gencore.MarshalJSON(sh.sections)
		if err != nil {
			t.Fatalf("marshal regenerated %s: %v", sh.name, err)
		}
		want := readCommitted(t, filepath.Join(corpusDirRel, sh.name))
		if !bytes.Equal(got, want) {
			t.Errorf("corpus shard %s drifted from committed snapshot; run `task docs-regen` and recommit "+
				"(regenerated %d bytes vs committed %d)", sh.name, len(got), len(want))
		}
	}
}

// TestCorpusPinManifestByteMatch asserts the regenerated manifest equals the
// committed manifest.json byte-for-byte. The manifest carries the spec git ref,
// the funpack version, and the per-source content hashes, so this catches a
// version/ref bump or a content-hash change the per-shard test would also flag,
// and additionally a manifest hand-edit that the shards alone cannot.
func TestCorpusPinManifestByteMatch(t *testing.T) {
	res := regenOrSkip(t)

	got, err := gencore.MarshalJSON(res.Manifest)
	if err != nil {
		t.Fatalf("marshal regenerated manifest: %v", err)
	}
	want := readCommitted(t, manifestPathRel)
	if !bytes.Equal(got, want) {
		t.Errorf("manifest.json drifted from committed snapshot; run `task docs-regen` and recommit\n"+
			"--- regenerated ---\n%s\n--- committed ---\n%s", got, want)
	}
}

// TestCorpusPinPerSourceHashes asserts the regenerated per-source content hashes
// match the committed manifest's, source-by-source — the granular signal naming
// WHICH source root drifted (spec, engine, or plugin), which the whole-file
// byte compare cannot. Recomputes each hash from the regenerated sections via
// gencore.HashSections so the assertion exercises the live hash function, not a
// value copied out of the manifest.
func TestCorpusPinPerSourceHashes(t *testing.T) {
	res := regenOrSkip(t)

	committed, err := docs.LoadManifest()
	if err != nil {
		t.Fatalf("LoadManifest: %v", err)
	}
	committedByRoot := map[string]string{}
	for _, s := range committed.Sources {
		committedByRoot[s.Root] = s.ContentHash
	}

	live := map[string]string{
		"funpack-spec/spec":          gencore.HashSections(res.Spec),
		"funpack-spec/stdlib/engine": gencore.HashSections(res.Engine),
		"plugins/funpack":            gencore.HashSections(res.Plugin),
	}
	for root, want := range committedByRoot {
		got, ok := live[root]
		if !ok {
			t.Errorf("committed manifest names source root %q that the generator no longer emits", root)
			continue
		}
		if got != want {
			t.Errorf("source root %q content hash drifted: regenerated %s, committed %s — run `task docs-regen`",
				root, got, want)
		}
	}
}

// TestMutatedManifestHashDetectedAsDrift is the negative-control unit test: it
// proves the per-source-hash comparison actually fires on a mutated hash. It
// flips one hex digit of a committed source hash in an in-memory copy and
// asserts the comparison (the same map-equality the pin check runs) reports the
// mismatch — independent of whether the spec sources are present, so it guards
// the drift logic itself even in a hermetic environment.
func TestMutatedManifestHashDetectedAsDrift(t *testing.T) {
	committed, err := docs.LoadManifest()
	if err != nil {
		t.Fatalf("LoadManifest: %v", err)
	}
	if len(committed.Sources) == 0 {
		t.Fatal("committed manifest records zero sources")
	}

	// Copy the committed hashes, then mutate exactly one source's hash.
	good := map[string]string{}
	for _, s := range committed.Sources {
		good[s.Root] = s.ContentHash
	}
	mutated := map[string]string{}
	for k, v := range good {
		mutated[k] = v
	}
	target := committed.Sources[0].Root
	mutated[target] = flipFirstHexDigit(good[target])
	if mutated[target] == good[target] {
		t.Fatalf("flipFirstHexDigit did not change the hash for %q", target)
	}

	mismatches := diffHashes(good, mutated)
	if len(mismatches) != 1 || mismatches[0] != target {
		t.Errorf("expected exactly one drift on %q, got %v", target, mismatches)
	}

	// Sanity: identical maps report no drift, so the detector is not trivially
	// always-positive.
	if got := diffHashes(good, good); len(got) != 0 {
		t.Errorf("identical hash maps reported drift: %v", got)
	}
}

// diffHashes returns the roots whose hashes differ between two source-hash maps,
// the comparison the pin check performs. Roots present in want but missing from
// got are reported too (a dropped source root is drift).
func diffHashes(want, got map[string]string) []string {
	var drifted []string
	for root, w := range want {
		if g, ok := got[root]; !ok || g != w {
			drifted = append(drifted, root)
		}
	}
	return drifted
}

// flipFirstHexDigit returns s with its first hex digit changed, so a content
// hash becomes a different-but-still-hex value. Empty input is returned as-is.
func flipFirstHexDigit(s string) string {
	if s == "" {
		return s
	}
	b := []byte(s)
	if b[0] == '0' {
		b[0] = '1'
	} else {
		b[0] = '0'
	}
	return string(b)
}
