// Surface-parity source loaders: the committed introspect-dump fixture (embedded,
// authoritative compiler surface) and the in-repo .fun signature files (the
// declared surface). The corpus side is the already-embedded Load().
package docs

import (
	"embed"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

//go:embed testdata/introspect.json
var introspectFixture embed.FS

const introspectFixturePath = "testdata/introspect.json"

// LoadIntrospectFixture reads the committed `funpack introspect` dump fixture
// (testdata/introspect.json) through go:embed, so the parity diff is hermetic —
// it needs no Odin toolchain and no funpack binary at test time. The fixture is
// regenerated by `task mcp:surface-dump-regen` and freshness-pinned against a
// live build by TestSurfaceDumpFixtureMatchesLiveBinary when Odin is available.
func LoadIntrospectFixture() ([]byte, error) {
	raw, err := introspectFixture.ReadFile(introspectFixturePath)
	if err != nil {
		return nil, fmt.Errorf("docs: read introspect fixture: %w", err)
	}
	return raw, nil
}

// CompilerModelFromFixture loads the committed dump fixture and parses it into
// the authoritative SurfaceModel — the convenience the parity gate consumes.
func CompilerModelFromFixture() (*SurfaceModel, error) {
	raw, err := LoadIntrospectFixture()
	if err != nil {
		return nil, err
	}
	return ParseDumpModel(raw)
}

// LoadFunSources reads the stdlib/engine/*.fun signature files from repoRoot into
// FunSource records keyed by their engine.<module> path (input.fun ->
// engine.input). The files are read in sorted filename order for determinism.
// Returns an error when the directory is absent so a misconfigured root fails
// loudly rather than yielding an empty (falsely-in-parity) model.
func LoadFunSources(repoRoot string) ([]FunSource, error) {
	engineDir := filepath.Join(repoRoot, "stdlib", "engine")
	entries, err := os.ReadDir(engineDir)
	if err != nil {
		return nil, fmt.Errorf("docs: read stdlib/engine: %w", err)
	}
	var names []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".fun") {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)

	sources := make([]FunSource, 0, len(names))
	for _, name := range names {
		raw, err := os.ReadFile(filepath.Join(engineDir, name))
		if err != nil {
			return nil, fmt.Errorf("docs: read %s: %w", name, err)
		}
		module := "engine." + strings.TrimSuffix(name, ".fun")
		sources = append(sources, FunSource{Module: module, Text: string(raw)})
	}
	return sources, nil
}
