// Surface-parity gate.
//
// THE DRIFT CLASS THIS CATCHES. The version-string corpus-pin check
// (corpus_pin_test.go) compares VERSION STRINGS and content hashes of the
// committed corpus against a regen of the same .fun/spec sources. It is
// structurally blind to an INTERNAL .fun-vs-compiler divergence at the SAME
// version: the docs corpus and the compiler can both report the same version,
// yet the compiler's typecheck allow-list (funpack/surface.odin) rejects surface
// the stdlib/engine/*.fun signature files (and the corpus distilled from them)
// advertise — code written exactly to the documented surface fails to compile.
// No version comparison can see that. This gate is the content-level check the
// version check cannot be: it
// diffs the docs corpus AND the .fun signature files against the compiler's
// AUTHORITATIVE surface dump (`funpack introspect`) and fails on a divergence,
// naming the diverging symbol and its direction.
//
// THE SOURCE OF TRUTH. Per ADR stdlib-surface-source-of-truth-parity-restore the
// spec and the .fun signature files ARE the source of truth; funpack/surface.odin
// must conform. The HARMFUL direction is therefore "the docs/.fun advertise X
// that the compiler dump LACKS" — an author reads X in the docs, writes it, and
// the compiler rejects it (the canonical break: a documented Color-palette member
// the compiler rejects). The OTHER direction (the dump
// recognizes X that no doc advertises) is a softer drift — a usable surface that
// is undocumented — and is reported too, so an undocumented compiler surface is
// also visible.
//
// THE GRANULARITY. The three sources render full signature strings differently
// (`extern fn count(self: View[T]) -> Int` in .fun, `fn(_) -> Int` in the dump),
// so a byte-for-byte signature comparison would be all false positives. The gate
// compares at the granularity where drift is MEANINGFUL and the three
// representations normalize to a common key: per-module declared NAMES, enum
// BARE-VARIANT SETS (the Color palette is the canonical example), and struct-payload
// VARIANT names plus their FIELD names (Color::Rgb{r,g,b}). Free-function and
// receiver-method SIGNATURE TEXT is intentionally out of scope (documented in
// excludedSurface) — the names are compared via the module-decl and method
// surfaces, but the rendered signature strings are not, because the three
// representations cannot be normalized to one key without re-implementing the
// compiler's type printer in Go.
//
// HOW IT SOURCES THE DUMP. The committed testdata/introspect.json fixture is the
// `funpack introspect` output, regenerated by `task mcp:surface-dump-regen`
// (builds a working-tree funpack and captures the dump) and freshness-pinned by
// TestSurfaceDumpFixtureMatchesLiveBinary, which rebuilds funpack and re-runs
// introspect WHEN the Odin toolchain is available, skipping clean otherwise
// (the same skip-when-sources-absent discipline the corpus pin uses). The parity
// diff itself reads the committed fixture, so it is hermetic — it runs under a
// bare `go test` with no Odin toolchain, reproducible in any CI that runs Go.
package docs

import (
	"fmt"
	"sort"
	"strings"
)

// SurfaceModel is the normalized, source-agnostic projection of an engine
// surface that the three sources (the compiler dump, the .fun signature files,
// the docs corpus) are each reduced to so they can be diffed on a common key.
// Every field is a deterministic set keyed by name — no signature strings, no
// source-specific spelling — so equality is meaningful across the three.
type SurfaceModel struct {
	// ModuleTypes maps a dotted module path (engine.render) to the set of TYPE
	// names it declares (Draw, Color, Flip, Align, Font). ONLY type declarations
	// (the dump's Type_Name kind; the .fun's enum/extern type/data) are modeled
	// here — NOT free functions or values. Type names normalize 1:1 across all
	// three sources, whereas a function's PLACEMENT differs structurally between
	// them: the dump splits free functions (modules[].decls Func) from receiver/
	// static/associated methods (the engine_methods/static_methods/associated
	// sections), while a .fun file declares both as top-level `extern fn`. Diffing
	// function names at the module-decl granularity is therefore all false
	// positives (every receiver method reads as docs-ahead). Function/value parity
	// is in excludedSurface; the divergence-relevant signal at this granularity is
	// TYPE presence (Font/Shape3/Volume/PathOp are the residual exemplars).
	ModuleTypes map[string]map[string]bool
	// EnumBareVariants maps an enum type name (Color) to its set of bare (no
	// payload) variant names (White, Black, …). The canonical Color-palette example.
	EnumBareVariants map[string]map[string]bool
	// StructVariants maps an enum type name (Color) to the set of its
	// struct-payload variant names (Rgb). Draw -> {Rect, Text, Camera, Sprite}.
	StructVariants map[string]map[string]bool
	// StructVariantFields maps "Type::Variant" (Color::Rgb) to the set of its
	// field names (r, g, b). Field TYPES are not compared (the three sources
	// spell types differently); field NAMES normalize cleanly.
	StructVariantFields map[string]map[string]bool
}

func newSurfaceModel() *SurfaceModel {
	return &SurfaceModel{
		ModuleTypes:         map[string]map[string]bool{},
		EnumBareVariants:    map[string]map[string]bool{},
		StructVariants:      map[string]map[string]bool{},
		StructVariantFields: map[string]map[string]bool{},
	}
}

// Direction names which side of a parity diff advertises a symbol the other
// lacks. A closed enum so a finding's direction is exhaustively switchable.
type Direction string

const (
	// DirDocsAheadOfCompiler is the HARMFUL direction of a same-version surface
	// divergence: the docs corpus or a .fun signature file advertises a symbol
	// the compiler dump does NOT admit. An author writes the documented symbol
	// and the compiler rejects it.
	DirDocsAheadOfCompiler Direction = "docs-advertises-compiler-lacks"
	// DirCompilerAheadOfDocs is the softer direction: the compiler dump admits a
	// symbol no doc source advertises — a usable but undocumented surface.
	DirCompilerAheadOfDocs Direction = "compiler-admits-docs-lack"
)

// ParityKind names the surface granularity a finding is at — the closed set of
// comparison axes (module decl, enum bare variant, struct variant, struct field).
type ParityKind string

const (
	KindModuleType    ParityKind = "module-type"
	KindEnumVariant   ParityKind = "enum-variant"
	KindStructVariant ParityKind = "struct-variant"
	KindStructField   ParityKind = "struct-field"
)

// Finding is one named parity divergence: WHAT diverged (the symbol), at WHICH
// granularity, in WHICH direction, and from WHICH doc source (the corpus or the
// .fun files). It carries everything the failure message needs to be actionable
// without re-deriving it — a future same-version surface divergence is named
// here, not discovered at a call site.
type Finding struct {
	Kind ParityKind
	// Direction is which side is ahead (see Direction).
	Direction Direction
	// Source is the doc-side source that produced this finding: "corpus" or
	// ".fun". Empty for a compiler-ahead finding (the doc side is what's missing,
	// and both doc sources are missing it together).
	Source string
	// Symbol is the fully-qualified diverging symbol, e.g. "engine.render::Align"
	// (module decl), "Color::Yellow" (enum variant), "Draw::Line" (struct
	// variant), "Color::Rgb.r" (struct field).
	Symbol string
}

func (f Finding) String() string {
	src := f.Source
	if src == "" {
		src = "docs"
	}
	switch f.Direction {
	case DirDocsAheadOfCompiler:
		return fmt.Sprintf("[%s] %s advertises %q which the compiler dump (funpack introspect) does NOT admit", f.Kind, src, f.Symbol)
	case DirCompilerAheadOfDocs:
		return fmt.Sprintf("[%s] the compiler dump admits %q which the docs do NOT advertise", f.Kind, f.Symbol)
	default:
		return fmt.Sprintf("[%s] %s: %q (%s)", f.Kind, src, f.Symbol, f.Direction)
	}
}

// excludedSurface documents the surface the gate intentionally does NOT compare,
// each with a one-line WHY so the exclusion is auditable rather than a silent
// hole. These are NOT divergences — they are comparison axes deliberately left
// out because the three sources cannot normalize to a common key there.
var excludedSurface = []string{
	// Free-FUNCTION and VALUE decls (engine.math.clamp/pi, engine.ui.button): NOT
	// compared at the module-decl granularity at all — and not by signature. The
	// dump splits free functions (modules[].decls Func) from receiver/static/
	// associated methods (separate sections), while a .fun file declares both as
	// top-level `extern fn`; so a function-name diff at module granularity reports
	// every receiver method (Input.pressed, View.count, Sound.gain) as docs-ahead.
	// Only TYPE decls (enum/extern type/data <-> Type_Name) normalize 1:1 across
	// the three sources, so only types are compared at module granularity (see
	// ModuleTypes). Function PRESENCE is implicitly covered where a function
	// returns/consumes a compared type; its rendered SIGNATURE is never compared
	// (that would mean re-implementing the compiler's type printer in Go).
	"free-function and value decls and their signatures (only TYPE decls are compared at module granularity)",
	// Receiver/static/associated method signatures (View.count, Sound.gain):
	// same spelling mismatch as free functions, plus the dump keys methods off a
	// receiver type the .fun expresses as a `self:` parameter. Method NAMES are
	// not currently in the doc-side model (the corpus distills them as engine
	// sections titled <module>.<fn>, indistinguishable from free functions), so
	// receiver-method parity is out of scope until a method-aware doc projection
	// exists.
	"receiver/static/associated method signatures and their receiver binding",
	// Combinator typing (engine.list.fold/map/filter, prelude.or_else): the dump
	// OMITS these from `signatures` entirely (surface_signatures returns found =
	// false) because their type is inferred at the call site, not fixed. There is
	// no signature to compare, by the compiler's own design.
	"combinator signatures (call-site-inferred; the dump omits them by design)",
	// Field TYPES of struct-payload variants (Color::Rgb.r: Fixed): the dump
	// renders the checker Type, the .fun renders the surface type token; field
	// NAMES normalize cleanly and ARE compared, field types are not (same
	// type-printer-parity problem as signatures).
	"struct-variant field TYPES (field NAMES are compared; types are not)",
	// Tuple-payload enum variants (a non-generic enum's `Name(T)` variant): the
	// dump's enum_variants section carries only BARE variants; a tuple-payload
	// variant is matched structurally at the call site, not enumerated in a probe
	// table. Comparing them would report every tuple variant as docs-ahead.
	"tuple-payload enum variants (matched structurally; the dump enumerates only bare variants)",
	// GENERIC enums (Option[T], Result[T,E]) wholesale: the dump never enumerates
	// a generic enum's variants in enum_variants (they are structurally matched,
	// so Option::None / Result::Ok have no probe-table row). The whole enum is
	// excluded — its variants are not compared in either direction.
	"generic (type-parameterized) enums and all their variants (structurally matched; absent from the dump's enum_variants)",
}

// residualOverDeclare is one allow-listed known-residual over-declaration: a
// symbol the .fun/corpus advertise that the compiler dump does NOT yet admit on
// the clean tree, BUT which is a tracked compiler GAP rather than a fresh
// regression. Each carries the WHY and the scrum tracker task so the hole is
// audited, not silent.
type residualOverDeclare struct {
	// Kind/Symbol match a Finding's Kind/Symbol exactly — the allow-list is keyed
	// by (Kind, Symbol).
	Kind   ParityKind
	Symbol string
	// Reason is the one-line WHY this over-declaration is currently expected.
	Reason string
}

// residualTrackerTask is the scrum task that owns shrinking the allow-list as
// each residual surface is restored in funpack/surface.odin. Named here (not
// embedded per-entry) because every entry shares it: the residuals are one class
// of compiler gap, tracked as one cross-team reconciliation task.
const residualTrackerTask = "residual-fun-over-declares-vs--mqjrunkb"

// residualOverDeclares is the EXPLICIT, AUDITED allow-list of known .fun/corpus
// over-declarations the compiler dump does not yet admit on the clean tree. The
// gate passes a DirDocsAheadOfCompiler finding ONLY if it is listed here; any
// over-declaration NOT on this list is a fresh same-version surface divergence and FAILS
// the gate, named. Per ADR stdlib-surface-source-of-truth-parity-restore each
// entry is a compiler GAP to be restored (or a deliberate prune) at the source —
// tracked by residualTrackerTask. As a restore lands, the dump grows to admit
// the symbol and the matching entry MUST be removed; the negative-control test
// TestNoResidualIsActuallyAdmitted asserts no allow-listed symbol is present in
// the live dump, so a stale entry fails loud rather than masking a real
// divergence.
//
// SCOPE NOTE: these residuals live in funpack/surface.odin and the runtime
// interpreter (the funpack/runtime write scopes); devtools owns only the gate
// that makes them visible. The list is the inventory the tracker task drains.
var residualOverDeclares = []residualOverDeclare{
	// --- Whole-type gaps: a type the .fun/spec declares that the compiler does
	// not recognize at all (absent from the dump). Each is one KindModuleType
	// entry; the type's variants are SUBSUMED (not separately allow-listed) by the
	// variant-finding subsumption in DiffSurfaces. Restoring the type's wiring in
	// surface.odin removes the entry.

	// render.fun declares Font (extern type) which is not in the compiler's
	// engine.render type decls. (Align is now admitted — readmitted by story
	// mechanical-variant-readmit — so it left this list.)
	{KindModuleType, "engine.render::Font", "extern Font type unimplemented in surface.odin"},
	// geom.fun's §03 vector-path geometry (Sketch builder + Path/PathOp) is wholly
	// unimplemented; Draw::Fill/Stroke (which name a Sketch) are the dependent
	// render gap below.
	{KindModuleType, "engine.geom::Sketch", "vector-path geometry unimplemented in surface.odin (engine.geom)"},
	{KindModuleType, "engine.geom::Path", "vector-path geometry unimplemented in surface.odin (engine.geom)"},
	{KindModuleType, "engine.geom::PathOp", "vector-path geometry unimplemented in surface.odin (engine.geom)"},
	// level.fun's §-level streaming surface (LevelHandle + Load/Unload outcomes +
	// trigger Volume) is wholly unimplemented in surface.odin.
	{KindModuleType, "engine.level::LevelHandle", "level-streaming surface unimplemented in surface.odin (engine.level)"},
	{KindModuleType, "engine.level::Load", "level-streaming surface unimplemented in surface.odin (engine.level)"},
	{KindModuleType, "engine.level::Unload", "level-streaming surface unimplemented in surface.odin (engine.level)"},
	{KindModuleType, "engine.level::Volume", "level-streaming surface unimplemented in surface.odin (engine.level)"},
	// model.fun's 3D modeling surface (Shape3 collision + the Anchors/Length/Solid
	// rig data) is wholly unimplemented in surface.odin.
	{KindModuleType, "engine.model::Shape3", "3D modeling surface unimplemented in surface.odin (engine.model)"},
	{KindModuleType, "engine.model::Anchors", "3D modeling surface unimplemented in surface.odin (engine.model)"},
	{KindModuleType, "engine.model::Length", "3D modeling surface unimplemented in surface.odin (engine.model)"},
	{KindModuleType, "engine.model::Solid", "3D modeling surface unimplemented in surface.odin (engine.model)"},
	// nav3.fun's whole 3D navigation surface is unimplemented (the 2D engine.nav
	// IS implemented); engine.nav's NavHandle handle type is also not in the dump.
	{KindModuleType, "engine.nav3::Nav3", "3D navigation surface unimplemented in surface.odin (engine.nav3)"},
	{KindModuleType, "engine.nav3::NavError3", "3D navigation surface unimplemented in surface.odin (engine.nav3)"},
	{KindModuleType, "engine.nav3::NavHandle3", "3D navigation surface unimplemented in surface.odin (engine.nav3)"},
	{KindModuleType, "engine.nav3::Path3", "3D navigation surface unimplemented in surface.odin (engine.nav3)"},
	{KindModuleType, "engine.nav::NavHandle", "baked-nav handle type unimplemented in surface.odin (engine.nav)"},
	// core.fun's TickRate config type is declared but not admitted.
	{KindModuleType, "engine.core::TickRate", "tick-rate config type unimplemented in surface.odin (engine.core)"},
	// ui.fun's Choice type is declared but not admitted.
	{KindModuleType, "engine.ui::Choice", "UI choice type unimplemented in surface.odin (engine.ui)"},
	// world.fun's Id/Owned handle types are declared but not admitted (the
	// implemented world surface is View/Ref/Spawn/Despawn).
	{KindModuleType, "engine.world::Id", "world handle type unimplemented in surface.odin (engine.world)"},
	{KindModuleType, "engine.world::Owned", "world handle type unimplemented in surface.odin (engine.world)"},

	// --- Per-variant gaps: a type the compiler DOES recognize, but missing
	// specific variants the .fun/spec declares. These are NOT subsumed (the type
	// exists), so each missing variant is allow-listed individually.

	// render.fun declares the full §20 Draw command set; the compiler admits only
	// Rect/Text/Camera/Sprite. Line/Fill/Stroke (the vector-path commands, which
	// name a geom Sketch) are unimplemented in surface.odin's struct_payload arms.
	{KindStructVariant, "Draw::Line", "vector-path draw command unimplemented in surface.odin (depends on engine.geom)"},
	{KindStructVariant, "Draw::Fill", "vector-path draw command unimplemented in surface.odin (depends on engine.geom)"},
	{KindStructVariant, "Draw::Stroke", "vector-path draw command unimplemented in surface.odin (depends on engine.geom)"},
	// NOTE: the full physical-key alphabet (Key:: B,C,E–L,N–V,X,Y,Z + Escape/Shift/
	// Tab), both extra local-player slots (PlayerId::P3/P4), and the full skeletal
	// Bone/Slot taxonomy (named joints + numbered Joint0–7 / Slot0–3) were all
	// readmitted into surface.odin by story mechanical-variant-readmit, so they are
	// now in parity and left this list. Only the feature-subsystem gaps above
	// (vector-path Draw commands, and the whole-type render/geom/level/model/nav3/
	// nav/core/ui/world subsystems) remain residual.
}

// residualKey is the (Kind, Symbol) lookup key the allow-list is matched on.
type residualKey struct {
	Kind   ParityKind
	Symbol string
}

// residualAllowSet builds the allow-list as a set for O(1) finding suppression.
func residualAllowSet() map[residualKey]bool {
	set := make(map[residualKey]bool, len(residualOverDeclares))
	for _, r := range residualOverDeclares {
		set[residualKey{r.Kind, r.Symbol}] = true
	}
	return set
}

// DiffSurfaces compares a documentation-side model (the corpus or the .fun files)
// against the authoritative compiler model and returns every divergence as a
// Finding, in deterministic (Kind, Direction, Symbol)-sorted order. docSource
// labels the doc side ("corpus" or ".fun") on each docs-ahead finding. The diff
// is symmetric: a symbol the docs advertise that the compiler lacks is
// DirDocsAheadOfCompiler; a symbol the compiler admits that the docs lack is
// DirCompilerAheadOfDocs. Allow-list suppression is NOT applied here — that is
// the gate's job (BlockingFindings), so a caller can inspect the full unfiltered
// drift.
func DiffSurfaces(doc, compiler *SurfaceModel, docSource string) []Finding {
	var findings []Finding

	// Module TYPE decls (Type_Name only — see ModuleTypes).
	for module, docTypes := range doc.ModuleTypes {
		compTypes := compiler.ModuleTypes[module]
		for name := range docTypes {
			if !compTypes[name] {
				findings = append(findings, Finding{
					Kind: KindModuleType, Direction: DirDocsAheadOfCompiler,
					Source: docSource, Symbol: module + "::" + name,
				})
			}
		}
	}
	for module, compTypes := range compiler.ModuleTypes {
		docTypes := doc.ModuleTypes[module]
		for name := range compTypes {
			if !docTypes[name] {
				findings = append(findings, Finding{
					Kind: KindModuleType, Direction: DirCompilerAheadOfDocs,
					Symbol: module + "::" + name,
				})
			}
		}
	}

	// known is the set of type names the compiler recognizes AT ALL (any module
	// declares it, or it carries enum/struct variants). A docs-ahead VARIANT
	// finding for a type the compiler does not know is SUBSUMED by the type-level
	// finding — reporting Shape3::Box/Capsule/Hull/Sphere separately when the
	// compiler has no Shape3 at all is noise, since the one KindModuleType finding
	// engine.model::Shape3 already names the gap. The compiler-ahead direction is
	// never subsumed (a recognized compiler type always has a module decl).
	known := compiler.knownTypes()

	// Enum bare variants.
	findings = append(findings, diffVariantSets(
		doc.EnumBareVariants, compiler.EnumBareVariants, KindEnumVariant, docSource, known)...)

	// Struct-payload variant names.
	findings = append(findings, diffVariantSets(
		doc.StructVariants, compiler.StructVariants, KindStructVariant, docSource, known)...)

	// Struct-payload variant FIELD names (only for variants present in both, so a
	// missing whole variant is reported once as KindStructVariant, not re-reported
	// per field).
	findings = append(findings, diffStructFields(doc, compiler, docSource)...)

	sortFindings(findings)
	return findings
}

// knownTypes returns the set of type names the compiler recognizes anywhere — a
// module type decl, an enum with variants, or a struct-payload owner. Used to
// subsume a docs-ahead variant finding under its type-level finding when the
// compiler does not know the type at all.
func (m *SurfaceModel) knownTypes() map[string]bool {
	known := map[string]bool{}
	for _, types := range m.ModuleTypes {
		for name := range types {
			known[name] = true
		}
	}
	for typeName := range m.EnumBareVariants {
		known[typeName] = true
	}
	for typeName := range m.StructVariants {
		known[typeName] = true
	}
	return known
}

// diffVariantSets diffs two type-name -> variant-name-set maps symmetrically,
// emitting one finding per variant ("Color::Yellow") that one side has and the
// other lacks. A docs-ahead variant whose type is NOT in knownCompilerTypes is
// suppressed — the type-level KindModuleType finding subsumes it (see the
// `known` comment in DiffSurfaces).
func diffVariantSets(doc, compiler map[string]map[string]bool, kind ParityKind, docSource string, knownCompilerTypes map[string]bool) []Finding {
	var findings []Finding
	for typeName, docVariants := range doc {
		if !knownCompilerTypes[typeName] {
			continue // subsumed by the type-level finding
		}
		compVariants := compiler[typeName]
		for v := range docVariants {
			if !compVariants[v] {
				findings = append(findings, Finding{
					Kind: kind, Direction: DirDocsAheadOfCompiler,
					Source: docSource, Symbol: typeName + "::" + v,
				})
			}
		}
	}
	for typeName, compVariants := range compiler {
		docVariants := doc[typeName]
		for v := range compVariants {
			if !docVariants[v] {
				findings = append(findings, Finding{
					Kind: kind, Direction: DirCompilerAheadOfDocs,
					Symbol: typeName + "::" + v,
				})
			}
		}
	}
	return findings
}

// diffStructFields diffs the field-name sets of struct-payload variants present
// in BOTH models, so the comparison reports a field add/drop (Color::Rgb gaining
// or losing a channel) on a variant the two sides agree exists. A variant only
// one side has is already reported at KindStructVariant; its fields are not
// re-diffed here.
func diffStructFields(doc, compiler *SurfaceModel, docSource string) []Finding {
	var findings []Finding
	for tv, docFields := range doc.StructVariantFields {
		compFields, both := compiler.StructVariantFields[tv]
		if !both {
			continue
		}
		for f := range docFields {
			if !compFields[f] {
				findings = append(findings, Finding{
					Kind: KindStructField, Direction: DirDocsAheadOfCompiler,
					Source: docSource, Symbol: tv + "." + f,
				})
			}
		}
		for f := range compFields {
			if !docFields[f] {
				findings = append(findings, Finding{
					Kind: KindStructField, Direction: DirCompilerAheadOfDocs,
					Symbol: tv + "." + f,
				})
			}
		}
	}
	return findings
}

// sortFindings orders findings deterministically by (Kind, Direction, Symbol) so
// a failure message and any test assertion are stable across runs.
func sortFindings(findings []Finding) {
	sort.Slice(findings, func(i, j int) bool {
		a, b := findings[i], findings[j]
		if a.Kind != b.Kind {
			return a.Kind < b.Kind
		}
		if a.Direction != b.Direction {
			return a.Direction < b.Direction
		}
		return a.Symbol < b.Symbol
	})
}

// BlockingFindings is the gate's verdict input: every parity finding across both
// doc sources, MINUS the suppressions. A DirDocsAheadOfCompiler finding is
// suppressed only if it is on the audited residualOverDeclares allow-list; a
// DirCompilerAheadOfDocs finding is reported but NON-blocking (an undocumented
// compiler surface is a softer drift than a documented-but-rejected one). The
// result is the set of findings that FAIL the gate — a fresh same-version
// surface divergence that nobody allow-listed. Empty result = the surface is in
// parity (modulo the audited residuals).
func BlockingFindings(corpusModel, funModel, compilerModel *SurfaceModel) []Finding {
	allow := residualAllowSet()
	corpusFindings := DiffSurfaces(corpusModel, compilerModel, "corpus")
	funFindings := DiffSurfaces(funModel, compilerModel, ".fun")

	var blocking []Finding
	seen := map[string]bool{} // dedupe identical (kind,dir,symbol,source) findings
	for _, f := range append(corpusFindings, funFindings...) {
		if f.Direction != DirDocsAheadOfCompiler {
			continue // compiler-ahead findings are reported elsewhere, never block
		}
		if allow[residualKey{f.Kind, f.Symbol}] {
			continue // audited residual
		}
		dedupe := string(f.Kind) + "|" + string(f.Direction) + "|" + f.Symbol + "|" + f.Source
		if seen[dedupe] {
			continue
		}
		seen[dedupe] = true
		blocking = append(blocking, f)
	}
	sortFindings(blocking)
	return blocking
}

// FormatBlockingFindings renders the gate's failure message: the count, then one
// named line per blocking finding, then the remediation pointer. Returns "" when
// there are no blocking findings.
func FormatBlockingFindings(blocking []Finding) string {
	if len(blocking) == 0 {
		return ""
	}
	var b strings.Builder
	fmt.Fprintf(&b, "surface-parity gate: %d divergence(s) where the docs advertise surface the compiler dump (funpack introspect) does NOT admit — a same-version surface divergence:\n", len(blocking))
	for _, f := range blocking {
		fmt.Fprintf(&b, "  - %s\n", f.String())
	}
	b.WriteString("Resolve at the source: restore the symbol in funpack/surface.odin (per ADR stdlib-surface-source-of-truth-parity-restore the spec/.fun are the source of truth) and the matching runtime interpreter arm, OR (if the symbol is a deliberate cut) prune it from the .fun signature file and regenerate the corpus. ")
	b.WriteString("If it is a known compiler gap, add it to residualOverDeclares in surface_parity.go with a WHY and the tracker task.")
	return b.String()
}
