package funpack

import "core:fmt"
import "core:strings"

REPORT_HEADER :: "asset report — GENERATED by the bake (release)"

REPORT_STRIP_LABEL :: "STRIP"

REPORT_STRIP_RATIONALE :: "(no handle reaches it — the 2D build draws the sprite, not the mesh)"

REPORT_LABEL_WIDTH :: 5

REPORT_LABEL_GAP :: "   "

REPORT_NAME_SIZE_WIDTH :: 14

REPORT_REFS_GAP :: "   "

Asset_Size :: struct {
	name: string,
	kb:   int,
}

asset_size_kb :: proc(sizes: []Asset_Size, name: string) -> int {
	for size in sizes {
		if size.name == name {
			return size.kb
		}
	}
	return 0
}

reach_for :: proc(reach: Asset_Reach, name: string) -> (entry: Asset_Reach_Entry, found: bool) {
	for e in reach.entries {
		if e.name == name {
			return e, true
		}
	}
	return Asset_Reach_Entry{}, false
}

emit_asset_report :: proc(
	reach: Asset_Reach,
	kept: []Asset_Entry,
	stripped: []Asset_Entry,
	sizes: []Asset_Size,
	allocator := context.allocator,
) -> string {
	b := strings.builder_make(allocator)

	baked := len(kept) + len(stripped)
	strings.write_string(&b, REPORT_HEADER)
	strings.write_string(&b, "\n\n")
	fmt.sbprintf(&b, "baked %d, stripped %d (unreferenced)\n\n", baked, len(stripped))

	for entry in kept {
		emit_report_asset_line(&b, reach, entry, sizes, false)
	}
	for entry in stripped {
		emit_report_asset_line(&b, reach, entry, sizes, true)
	}

	shipped_kb := sum_asset_sizes(kept, sizes)
	stripped_kb := sum_asset_sizes(stripped, sizes)
	strings.write_string(&b, "\n")
	fmt.sbprintf(&b, "shipped %d KB across %d assets; %d KB stripped.\n", shipped_kb, len(kept), stripped_kb)
	fmt.sbprintf(&b, "cache: %d hits, 0 misses (incremental).\n", baked)

	return strings.to_string(b)
}

emit_report_asset_line :: proc(
	b: ^strings.Builder,
	reach: Asset_Reach,
	entry: Asset_Entry,
	sizes: []Asset_Size,
	is_stripped: bool,
) {
	verdict, _ := reach_for(reach, entry.name)
	kb := asset_size_kb(sizes, entry.name)

	label := is_stripped ? REPORT_STRIP_LABEL : asset_kind_label(entry.kind)
	name_field := is_stripped ? strings.concatenate({asset_kind_label(entry.kind), " ", entry.name}, context.temp_allocator) : entry.name
	tail := is_stripped ? REPORT_STRIP_RATIONALE : strings.concatenate({"<- ", verdict.referencer}, context.temp_allocator)

	strings.write_string(b, "  ")
	write_left_justified(b, label, REPORT_LABEL_WIDTH)
	strings.write_string(b, REPORT_LABEL_GAP)
	write_name_and_size(b, name_field, kb)
	strings.write_string(b, REPORT_REFS_GAP)
	fmt.sbprintf(b, "refs %d", verdict.ref_count)
	strings.write_string(b, REPORT_REFS_GAP)
	strings.write_string(b, tail)
	strings.write_string(b, "\n")
}

write_name_and_size :: proc(b: ^strings.Builder, name: string, kb: int) {
	size_text := fmt.tprintf("%d", kb)
	pad := REPORT_NAME_SIZE_WIDTH - len(name) - len(size_text)
	if pad < 1 {
		pad = 1
	}
	strings.write_string(b, name)
	for _ in 0 ..< pad {
		strings.write_byte(b, ' ')
	}
	strings.write_string(b, size_text)
	strings.write_string(b, " KB")
}

write_left_justified :: proc(b: ^strings.Builder, text: string, width: int) {
	strings.write_string(b, text)
	for _ in len(text) ..< width {
		strings.write_byte(b, ' ')
	}
}

asset_kind_label :: proc(kind: Asset_Kind) -> string {
	return asset_kind_word(kind)
}

sum_asset_sizes :: proc(entries: []Asset_Entry, sizes: []Asset_Size) -> int {
	total := 0
	for entry in entries {
		total += asset_size_kb(sizes, entry.name)
	}
	return total
}
