// The §19 §5 asset report emitter: the human-readable bake summary release emits
// so "truncation is never silent" (§19.5). It renders the reference graph the
// release strip (asset_strip.odin) computed — counts, sizes, what each asset's
// referencer is, and what was stripped — into the canonical text the committed
// exemplar examples/assets/assets/assets.report.txt pins byte-for-byte. The report
// is downstream of the strip: it reads the Asset_Reach (the refs/referencer
// columns) and the kept/stripped partition (the per-asset lines and footer sums)
// the strip produced, and joins them with the per-asset sizes the baker supplies.
//
// LAYOUT (column-exact, from the committed exemplar's bytes):
//   asset report — GENERATED by the bake (release)
//   <blank>
//   baked N, stripped M (unreferenced)
//   <blank>
//     LABEL   NAME________SIZE KB   refs C   TAIL          (one per asset)
//     …
//   <blank>
//   shipped S KB across K assets; T KB stripped.
//   cache: H hits, 0 misses (incremental).
// where LABEL is the kind for a kept asset and "STRIP" for a stripped one (the
// stripped line then carries "kind name" in the name field), NAME left-justified
// and SIZE right-justified share a fixed 14-column field, and TAIL is the kept
// asset's "<- referencer" edge or the stripped asset's "(rationale)".
//
// PURITY (spec §09, §29): emission is a pure function of (reach, kept, stripped,
// sizes) — every column width is a constant, every walk is slice-order, the cache
// line is derived (all baked = hits, an incremental bake misses nothing), so the
// report reads no clock, no path, no host bytes, and two emissions of the same
// inputs are byte-identical.
package funpack

import "core:fmt"
import "core:strings"

// REPORT_HEADER is the file-leading line of every release asset report: fixed
// boilerplate naming the report and its release provenance, verbatim from the
// committed exemplar's line 1 (the em-dash kept so the byte comparison exercises
// multibyte content, like the seam emitter's module doc).
REPORT_HEADER :: "asset report — GENERATED by the bake (release)"

// REPORT_STRIP_LABEL is the LABEL column for a stripped asset: "STRIP" stands
// where a kept asset shows its kind, so the eye catches the dropped rows. The
// stripped line then renders "kind name" in the name field (the kind a kept line
// puts in the label column moves inline), per the exemplar's "STRIP   model coin".
REPORT_STRIP_LABEL :: "STRIP"

// REPORT_STRIP_RATIONALE is the stripped asset's TAIL: the §19.5 dead-asset
// rationale verbatim from the exemplar, naming WHY no handle reaches the model
// coin (the 2D build draws the sprite atlas, not the mesh). It replaces the
// "<- referencer" edge a kept asset shows, since a dead asset has no referencer.
REPORT_STRIP_RATIONALE :: "(no handle reaches it — the 2D build draws the sprite, not the mesh)"

// REPORT_LABEL_WIDTH is the LABEL column width (the kind or "STRIP"), left-
// justified, after the 2-space line indent. The asset kinds and "STRIP" are all
// exactly 5 glyphs in the closed set, so this both names the contract and pads any
// future shorter label to the column the name field starts after.
REPORT_LABEL_WIDTH :: 5

// REPORT_LABEL_GAP is the fixed run of spaces between the LABEL column and the
// name field — the exemplar's 3 spaces after "atlas"/"audio"/"STRIP".
REPORT_LABEL_GAP :: "   "

// REPORT_NAME_SIZE_WIDTH is the combined width of the name+size field: the name is
// left-justified and the size value is right-justified within it, so a short name
// and a wide size still align the " KB" suffix (the exemplar's "pickups      6"
// and "model coin  12" both end the number at the same column). 14 columns from
// the exemplar's byte layout.
REPORT_NAME_SIZE_WIDTH :: 14

// REPORT_REFS_GAP is the fixed run of spaces between " KB" and the "refs" column,
// and again between the refs count and the TAIL — the exemplar's 3 spaces in both
// gaps.
REPORT_REFS_GAP :: "   "

// Asset_Size is one asset's baked size in whole kilobytes, keyed by its registered
// name so the report can look a kept or stripped entry's size up by name (the
// kept/stripped partition is Asset_Entry slices; the sizes ride parallel, keyed by
// name, so neither has to embed the other's data). KB is the unit the §5 report
// renders ("6 KB"); the baker rounds to whole KB before handing sizes here.
Asset_Size :: struct {
	name: string,
	kb:   int,
}

// asset_size_kb looks an asset's size up by name in the parallel sizes slice,
// returning 0 when the name is absent (a missing size renders "0 KB" rather than
// crashing the report; the byte-match path always supplies a size per asset). The
// slice is small (one entry per baked asset), so a linear scan beats a map whose
// iteration order the report cannot depend on — the same determinism tripwire the
// manifest reader and registry hold.
asset_size_kb :: proc(sizes: []Asset_Size, name: string) -> int {
	for size in sizes {
		if size.name == name {
			return size.kb
		}
	}
	return 0
}

// reach_for asset looks a name up in the reach's per-entry verdicts, returning the
// entry (refs count + referencer) and whether it was found. The report reads each
// kept/stripped asset's refs/referencer columns through here, since the partition
// slices carry only the manifest fields, not the reachability verdict.
reach_for :: proc(reach: Asset_Reach, name: string) -> (entry: Asset_Reach_Entry, found: bool) {
	for e in reach.entries {
		if e.name == name {
			return e, true
		}
	}
	return Asset_Reach_Entry{}, false
}

// emit_asset_report renders the §5 release asset report to canonical text, byte-
// matching the committed exemplar. It joins the strip's outputs: the kept/stripped
// partition (the per-asset lines and the footer sums), the reach (each asset's
// refs count and referencer), and the per-asset sizes. Kept assets render first in
// their partition order, then stripped assets, each as one column-aligned line;
// the header counts and footer sums are derived from the partition (baked = kept +
// stripped, shipped = sum of kept sizes across len(kept) assets, stripped sum
// likewise) and the cache line is the incremental all-hit derivation (every baked
// asset is a cache hit, an incremental bake misses nothing). The returned string
// is allocated in `allocator` and ends in exactly one newline.
emit_asset_report :: proc(
	reach: Asset_Reach,
	kept: []Asset_Entry,
	stripped: []Asset_Entry,
	sizes: []Asset_Size,
	allocator := context.allocator,
) -> string {
	b := strings.builder_make(allocator)

	baked := len(kept) + len(stripped)
	strings.write_string(&b, REPORT_HEADER)
	strings.write_string(&b, "\n\n")
	fmt.sbprintf(&b, "baked %d, stripped %d (unreferenced)\n\n", baked, len(stripped))

	for entry in kept {
		emit_report_asset_line(&b, reach, entry, sizes, false)
	}
	for entry in stripped {
		emit_report_asset_line(&b, reach, entry, sizes, true)
	}

	shipped_kb := sum_asset_sizes(kept, sizes)
	stripped_kb := sum_asset_sizes(stripped, sizes)
	strings.write_string(&b, "\n")
	fmt.sbprintf(&b, "shipped %d KB across %d assets; %d KB stripped.\n", shipped_kb, len(kept), stripped_kb)
	// The cache line is the incremental all-hit derivation: every baked asset is a
	// cache hit (the content-addressed store already holds it), and an incremental
	// bake misses nothing — so hits = baked, misses = 0.
	fmt.sbprintf(&b, "cache: %d hits, 0 misses (incremental).\n", baked)

	return strings.to_string(b)
}

// emit_report_asset_line writes one asset's column-aligned line. A kept asset's
// LABEL is its kind and its TAIL is the "<- referencer" edge; a stripped asset's
// LABEL is "STRIP", its name field carries "kind name" inline, and its TAIL is the
// dead-asset rationale. The name+size field left-justifies the name and right-
// justifies the size within REPORT_NAME_SIZE_WIDTH so the " KB" suffix aligns
// across rows of differing name and size widths.
emit_report_asset_line :: proc(
	b: ^strings.Builder,
	reach: Asset_Reach,
	entry: Asset_Entry,
	sizes: []Asset_Size,
	is_stripped: bool,
) {
	verdict, _ := reach_for(reach, entry.name)
	kb := asset_size_kb(sizes, entry.name)

	label := is_stripped ? REPORT_STRIP_LABEL : asset_kind_label(entry.kind)
	// A stripped line shows "kind name" in the name field (its kind moved inline
	// because the LABEL column holds "STRIP"); a kept line shows the bare name.
	name_field := is_stripped ? strings.concatenate({asset_kind_label(entry.kind), " ", entry.name}, context.temp_allocator) : entry.name
	tail := is_stripped ? REPORT_STRIP_RATIONALE : strings.concatenate({"<- ", verdict.referencer}, context.temp_allocator)

	strings.write_string(b, "  ")
	write_padded_right(b, label, REPORT_LABEL_WIDTH)
	strings.write_string(b, REPORT_LABEL_GAP)
	write_name_and_size(b, name_field, kb)
	strings.write_string(b, REPORT_REFS_GAP)
	fmt.sbprintf(b, "refs %d", verdict.ref_count)
	strings.write_string(b, REPORT_REFS_GAP)
	strings.write_string(b, tail)
	strings.write_string(b, "\n")
}

// write_name_and_size writes the name+size field: the name left-justified, then the
// size value right-justified so the digits end at the field's last column, then a
// single space and "KB". The two sub-fields share REPORT_NAME_SIZE_WIDTH columns,
// so a short name with a wide number and a long name with a narrow number both end
// the number at the same column (the exemplar's "pickups      6" / "model coin  12").
write_name_and_size :: proc(b: ^strings.Builder, name: string, kb: int) {
	size_text := fmt.tprintf("%d", kb)
	// The name and the size digits share the field; the gap between them is
	// whatever columns the two leave, so the size right-aligns to the field's end.
	pad := REPORT_NAME_SIZE_WIDTH - len(name) - len(size_text)
	if pad < 1 {
		pad = 1 // always at least one space between name and size
	}
	strings.write_string(b, name)
	for _ in 0 ..< pad {
		strings.write_byte(b, ' ')
	}
	strings.write_string(b, size_text)
	strings.write_string(b, " KB")
}

// write_padded_right writes `text` left-justified in a `width`-column field,
// padding with trailing spaces; a text already at or over the width is written
// verbatim (no truncation). The LABEL column uses this so a kind shorter than the
// column still lands the name field at its fixed start.
write_padded_right :: proc(b: ^strings.Builder, text: string, width: int) {
	strings.write_string(b, text)
	for _ in len(text) ..< width {
		strings.write_byte(b, ' ')
	}
}

// asset_kind_label maps an Asset_Kind onto its lowercase report label — the LABEL
// column for a kept asset and the inline kind prefix for a stripped one. The
// mapping is total over the closed kind set: Model → "model", Atlas → "atlas",
// Audio → "audio", Tileset → "tileset" (the kind word the §5 report renders,
// distinct from the handle TYPE asset_handle_type renders for the seam).
asset_kind_label :: proc(kind: Asset_Kind) -> string {
	switch kind {
	case .Model:
		return "model"
	case .Atlas:
		return "atlas"
	case .Audio:
		return "audio"
	case .Tileset:
		return "tileset"
	}
	return ""
}

// sum_asset_sizes totals the KB of every asset in `entries`, looking each size up
// by name in the parallel sizes slice — the footer's "shipped S KB" (over kept) and
// "T KB stripped" (over stripped). An asset with no size contributes 0.
sum_asset_sizes :: proc(entries: []Asset_Entry, sizes: []Asset_Size) -> int {
	total := 0
	for entry in entries {
		total += asset_size_kb(sizes, entry.name)
	}
	return total
}
