// The `funpack fmt` front-door verb: the §02 mandatory canonical formatter
// applied over the §14 project tree. `funpack fmt` rewrites every AUTHORED
// source (src/*.fun) in place to its render_canonical projection; `funpack
// fmt --check` is the verdict-only twin — it adjudicates drift and writes
// NOTHING, mirroring `funpack check`'s ethos (spec §29 §3: build's verdict
// with the write deleted).
//
// Exit contract, consistent with the verb family (§29 §3):
//   - 2 — a malformed tree (read_project refusal) or any source the §02
//     grammar cannot parse (a compile error is never a counted drift), or a
//     host IO failure reading/writing a source;
//   - 1 — `--check` only: at least one authored source drifts from its
//     canonical form (the counted tier, mirroring `funpack test`'s counted
//     assertion failures — drift is tallied, never refused);
//   - 0 — every authored source is canonical (`--check`), or the write pass
//     completed (`fmt`).
// Stdout is operator-facing and ADVISORY (the drifted/wrote path lines, the
// clean verdict); the machine contract is exclusively the exit code.
//
// Generated gen/*.gen.fun seams are deliberately SKIPPED: a committed seam is
// the bake emitter's byte contract (gen_emit.odin), diffed byte-exact by the
// golden seam harness — reformatting it would manufacture stale-seam build
// errors. fmt owns authored bytes; the emitter owns generated bytes.
package funpack

import "core:fmt"
import "core:os"
import "core:strings"

// Fmt_Mode selects the verb's two faces: Write rewrites drifting sources in
// place; Check adjudicates and writes nothing.
Fmt_Mode :: enum {
	Write,
	Check,
}

// parse_fmt_mode maps the fmt verb's arguments to its Fmt_Mode, mirroring
// parse_build_mode: no argument is Write (the in-place formatter), exactly
// `--check` is Check (verdict-only). Any other argument is a usage error
// (ok = false → usage + exit 2), so a misspelled flag never silently rewrites
// the tree.
parse_fmt_mode :: proc(args: []string) -> (mode: Fmt_Mode, ok: bool) {
	if len(args) == 0 {
		return .Write, true
	}
	if len(args) == 1 && args[0] == "--check" {
		return .Check, true
	}
	return .Write, false
}

// run_fmt_verb drives the fmt verb at the working directory. The body lives
// in the root-parameterized fmt_verb_exit (the run_check_verb precedent) so
// the exit contract is unit-tested against temp trees; main always passes ".".
run_fmt_verb :: proc(mode: Fmt_Mode) -> int {
	return fmt_verb_exit(".", mode)
}

// fmt_verb_exit is the fmt exit contract over one §14 tree: read the project
// (a refusal is exit 2), walk every authored source in the project's
// deterministic order, parse it (a parse error is exit 2 — a compile error is
// never a counted drift), and compare its bytes against render_canonical's
// projection. Write mode rewrites a drifting source in place (an IO failure
// is exit 2) and exits 0; Check mode tallies drifting sources, prints each
// path as an advisory stdout line, and exits 1 on any drift, 0 when the whole
// tree is canonical. Generated seams (gen/*.gen.fun) are skipped — the bake
// emitter owns their bytes.
fmt_verb_exit :: proc(root: string, mode: Fmt_Mode) -> int {
	project, project_err := read_project(root)
	if project_err != .None {
		fmt.eprintfln("funpack fmt: %v", project_err)
		return 2
	}
	drifted := 0
	for source in project.sources {
		if strings.has_suffix(source.path, GEN_SUFFIX) {
			continue
		}
		bytes, read_err := os.read_entire_file_from_path(source.path, context.temp_allocator)
		if read_err != nil {
			fmt.eprintfln("funpack fmt: %s: %v", source.path, read_err)
			return 2
		}
		ast, parse_err := stage_parse(stage_lex(string(bytes)))
		if parse_err != .None {
			fmt.eprintfln("funpack fmt: %s: %v", source.path, parse_err)
			return 2
		}
		canonical := render_canonical(ast, context.temp_allocator)
		if canonical == string(bytes) {
			continue
		}
		switch mode {
		case .Write:
			if os.write_entire_file(source.path, transmute([]u8)canonical) != nil {
				fmt.eprintfln("funpack fmt: %s: write failed", source.path)
				return 2
			}
			fmt.printfln("funpack fmt: wrote %s", source.path)
		case .Check:
			drifted += 1
			fmt.printfln("funpack fmt: %s drifts from canonical form", source.path)
		}
	}
	if mode == .Check && drifted != 0 {
		return 1
	}
	if mode == .Check {
		fmt.println("funpack fmt: clean")
	}
	return 0
}
