// Code generated by internal/contract/gen; DO NOT EDIT.
//
// Source of truth: contract/funpack-api.json. Regenerate with
// `go run ./internal/contract/gen` from the mcp module. See ADR
// 2026-06-15-funpack-api-contract-dual-codegen.
package contract

import "encoding/json"

// ContractVersion is the funpack-api.json schema revision this code was generated from.
const ContractVersion = 1

// VersionInfo is the decoded shape of `funpack version --json`. An absent schema
// key in Schemas means the build does not expose that schema yet (not an error).
type VersionInfo struct {
	Version string         `json:"version"`
	Schemas map[string]int `json:"schemas"`
}

// VersionArgv is the argv that produces VersionInfo JSON on stdout.
var VersionArgv = []string{"version", "--json"}

// Schema-name constants — the keys VersionInfo.Schemas may carry.
const (
	SchemaArtifact   = "artifact"
	SchemaIndex      = "index"
	SchemaIntrospect = "introspect"
)

// VersionRange is the inclusive [Min, Max] schema-version window this MCP build accepts.
type VersionRange struct {
	Min int
	Max int
}

// Contains reports whether v falls within the inclusive range.
func (r VersionRange) Contains(v int) bool { return v >= r.Min && v <= r.Max }

// Supported is the MCP compat policy: per-schema the funpack versions this build
// accepts. Preflight refuses a PRESENT schema outside its range; an ABSENT schema
// never refuses (§29 Index-Contract discipline).
var Supported = map[string]VersionRange{
	SchemaArtifact:   {Min: 18, Max: 18},
	SchemaIndex:      {Min: 6, Max: 6},
	SchemaIntrospect: {Min: 1, Max: 1},
}

// ProtocolVersion is the §28 exact-match envelope version every message stamps as `v`.
const ProtocolVersion = 1

// Transport names the §28 wire transport.
const Transport = "ndjson-duplex-loopback"

// --- §28 envelopes -----------------------------------------------------------
//
// Three closed message kinds, each a fixed-order field tuple, versioned exact-match.
// Every envelope stamps `v` == ProtocolVersion; a consumer refuses a version or
// field-shape mismatch rather than best-effort parsing.

// Request is the §28 request envelope.
//
// v=protocol version; id correlates the response; cmd is the command name;
// args is its argument object
type Request struct {
	V    int             `json:"v"`
	ID   int64           `json:"id"`
	Cmd  string          `json:"cmd"`
	Args json.RawMessage `json:"args,omitempty"`
}

// Response is the §28 response envelope.
//
// ok is the success boolean; exactly one of result (when ok) or error
// (otherwise) is present — never both, never neither
//
// Exactly-one invariant: when Ok is true, Result is non-nil and Error is nil; when
// Ok is false, Error is non-nil and Result is nil — never both, never neither.
type Response struct {
	V      int              `json:"v"`
	ID     int64            `json:"id"`
	Ok     bool             `json:"ok"`
	Cmd    string           `json:"cmd"`
	Result *json.RawMessage `json:"result,omitempty"`
	Error  *string          `json:"error,omitempty"`
}

// Event is the §28 event envelope.
//
// unsolicited push correlated by `event` name (not id); breakpoint_hit and
// watch_fired carry probe payloads (target and value)
//
// The payload is open: an unsolicited push correlated by Name (not an id).
// Payload captures every field beyond `v`/`event` (e.g. breakpoint_hit/watch_fired
// carry target and value).
type Event struct {
	V       int                        `json:"v"`
	Name    string                     `json:"event"`
	Payload map[string]json.RawMessage `json:"-"`
}

// --- §28 command taxonomy ----------------------------------------------------

// Class is a command's determinism class. observe = non-perturbing (reads the
// canonical chain by default, accepts an optional `branch` arg); control =
// perturbing -> forks a non-warranted branch off a snapshot.
type Class string

const (
	ClassObserve Class = "observe"
	ClassControl Class = "control"
)

// Command is a §28 command name.
type Command string

const (
	// group "break" (class observe)
	CmdBreak Command = "break"
	CmdWatch Command = "watch"
	CmdClear Command = "clear"

	// group "control" (class control)
	CmdInjectInput Command = "inject_input"
	CmdSet         Command = "set"
	CmdSpawn       Command = "spawn"
	CmdDespawn     Command = "despawn"
	CmdEmit        Command = "emit"
	CmdReload      Command = "reload"
	CmdBranch      Command = "branch"
	CmdCheckout    Command = "checkout"

	// group "inspect" (class observe)
	CmdSignals        Command = "signals"
	CmdPipeline       Command = "pipeline"
	CmdTrace          Command = "trace"
	CmdDiff           Command = "diff"
	CmdReplayBehavior Command = "replay_behavior"
	CmdDrawList       Command = "draw_list"
	CmdScreenshot     Command = "screenshot"

	// group "self_heal" (class observe)
	CmdCaptureTest Command = "capture_test"
	CmdAudit       Command = "audit"

	// group "time" (class observe)
	CmdLoad   Command = "load"
	CmdRun    Command = "run"
	CmdPause  Command = "pause"
	CmdStep   Command = "step"
	CmdRewind Command = "rewind"
	CmdReset  Command = "reset"
	CmdStatus Command = "status"
)

// commandClass maps each Command to the determinism Class of its group.
var commandClass = map[Command]Class{
	CmdBreak:          ClassObserve,
	CmdWatch:          ClassObserve,
	CmdClear:          ClassObserve,
	CmdInjectInput:    ClassControl,
	CmdSet:            ClassControl,
	CmdSpawn:          ClassControl,
	CmdDespawn:        ClassControl,
	CmdEmit:           ClassControl,
	CmdReload:         ClassControl,
	CmdBranch:         ClassControl,
	CmdCheckout:       ClassControl,
	CmdSignals:        ClassObserve,
	CmdPipeline:       ClassObserve,
	CmdTrace:          ClassObserve,
	CmdDiff:           ClassObserve,
	CmdReplayBehavior: ClassObserve,
	CmdDrawList:       ClassObserve,
	CmdScreenshot:     ClassObserve,
	CmdCaptureTest:    ClassObserve,
	CmdAudit:          ClassObserve,
	CmdLoad:           ClassObserve,
	CmdRun:            ClassObserve,
	CmdPause:          ClassObserve,
	CmdStep:           ClassObserve,
	CmdRewind:         ClassObserve,
	CmdReset:          ClassObserve,
	CmdStatus:         ClassObserve,
}

// commandGroup maps each Command to the name of the group that declares it.
var commandGroup = map[Command]string{
	CmdBreak:          "break",
	CmdWatch:          "break",
	CmdClear:          "break",
	CmdInjectInput:    "control",
	CmdSet:            "control",
	CmdSpawn:          "control",
	CmdDespawn:        "control",
	CmdEmit:           "control",
	CmdReload:         "control",
	CmdBranch:         "control",
	CmdCheckout:       "control",
	CmdSignals:        "inspect",
	CmdPipeline:       "inspect",
	CmdTrace:          "inspect",
	CmdDiff:           "inspect",
	CmdReplayBehavior: "inspect",
	CmdDrawList:       "inspect",
	CmdScreenshot:     "inspect",
	CmdCaptureTest:    "self_heal",
	CmdAudit:          "self_heal",
	CmdLoad:           "time",
	CmdRun:            "time",
	CmdPause:          "time",
	CmdStep:           "time",
	CmdRewind:         "time",
	CmdReset:          "time",
	CmdStatus:         "time",
}

// Commands is every §28 command in contract order (groups sorted, commands as declared).
var Commands = []Command{
	CmdBreak,
	CmdWatch,
	CmdClear,
	CmdInjectInput,
	CmdSet,
	CmdSpawn,
	CmdDespawn,
	CmdEmit,
	CmdReload,
	CmdBranch,
	CmdCheckout,
	CmdSignals,
	CmdPipeline,
	CmdTrace,
	CmdDiff,
	CmdReplayBehavior,
	CmdDrawList,
	CmdScreenshot,
	CmdCaptureTest,
	CmdAudit,
	CmdLoad,
	CmdRun,
	CmdPause,
	CmdStep,
	CmdRewind,
	CmdReset,
	CmdStatus,
}

// ClassOf returns the determinism class of cmd and whether cmd is a known command.
func ClassOf(cmd Command) (Class, bool) {
	class, ok := commandClass[cmd]
	return class, ok
}

// GroupOf returns the declaring group of cmd and whether cmd is a known command.
func GroupOf(cmd Command) (string, bool) {
	group, ok := commandGroup[cmd]
	return group, ok
}

// IsControl reports whether cmd is a perturbing control command.
func IsControl(cmd Command) bool { return commandClass[cmd] == ClassControl }

// EventName is a §28 async event name.
type EventName string

const (
	EventBreakpointHit EventName = "breakpoint_hit"
	EventWatchFired    EventName = "watch_fired"
	EventDiverged      EventName = "diverged"
)

// Events is every §28 event name in contract order.
var Events = []EventName{
	EventBreakpointHit,
	EventWatchFired,
	EventDiverged,
}
