package contract

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// repoRootFromTest walks up from the test's working directory to the dir holding
// a VERSION file — the repo root — mirroring the generator's own resolution so the
// sync tests locate the contract, the committed Go file, and the Odin sources the
// same way the generator does.
func repoRootFromTest(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	for {
		if fi, err := os.Stat(filepath.Join(dir, "VERSION")); err == nil && !fi.IsDir() {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatalf("no VERSION file found walking up from test cwd")
		}
		dir = parent
	}
}

// runGen invokes the real generator (`go run ./internal/contract/gen`) from the
// mcp module with the given args and returns its combined output on failure. It
// exercises the generator end-to-end rather than re-implementing its rendering.
func runGen(t *testing.T, root string, args ...string) {
	t.Helper()
	cmd := exec.Command("go", append([]string{"run", "./internal/contract/gen"}, args...)...)
	cmd.Dir = filepath.Join(root, "mcp")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go run gen %v: %v\n%s", args, err, out)
	}
}

// TestGeneratedGoIsFresh regenerates the Go side into a temp path and asserts it
// byte-matches the committed contract_gen.go. It fails if someone hand-edits the
// generated file or bumps the contract without regenerating — the staleness gate
// that keeps the source of truth and the checked-in code in lockstep.
func TestGeneratedGoIsFresh(t *testing.T) {
	root := repoRootFromTest(t)
	committedPath := filepath.Join(root, "mcp", "internal", "contract", "contract_gen.go")

	committed, err := os.ReadFile(committedPath)
	if err != nil {
		t.Fatalf("read committed %s: %v", committedPath, err)
	}

	freshPath := filepath.Join(t.TempDir(), "contract_gen.go")
	runGen(t, root, "-go-out", freshPath)

	fresh, err := os.ReadFile(freshPath)
	if err != nil {
		t.Fatalf("read regenerated %s: %v", freshPath, err)
	}

	if string(committed) != string(fresh) {
		t.Fatalf("contract_gen.go is stale — regenerate with `go run ./internal/contract/gen`.\n"+
			"committed %d bytes, fresh %d bytes", len(committed), len(fresh))
	}
}

// TestGeneratedOdinIsWellFormed exercises the generator's Odin emission into a
// temp path (it is never committed under funpack/** by this module) and asserts
// the output is non-empty and well-formed-looking: the DO-NOT-EDIT header, the
// `package funpack` clause, and at least one §28 command/event const and one
// schema-name const. The funpack-team task lands the real file via -odin-out.
func TestGeneratedOdinIsWellFormed(t *testing.T) {
	root := repoRootFromTest(t)
	odinPath := filepath.Join(t.TempDir(), "api_contract.gen.odin")
	runGen(t, root, "-odin-out", odinPath)

	raw, err := os.ReadFile(odinPath)
	if err != nil {
		t.Fatalf("read generated Odin %s: %v", odinPath, err)
	}
	got := string(raw)
	if len(strings.TrimSpace(got)) == 0 {
		t.Fatal("generated Odin output is empty")
	}

	wantSubstrings := []string{
		"// Code generated by mcp/internal/contract/gen; DO NOT EDIT.",
		"package funpack",
		"API_CONTRACT_VERSION ::",
		"SCHEMA_NAME_ARTIFACT :: \"artifact\"",
		"CMD_LOAD :: \"load\"",
		"EVENT_BREAKPOINT_HIT :: \"breakpoint_hit\"",
		"ENVELOPE_RESPONSE_FIELD_OK :: \"ok\"",
	}
	for _, want := range wantSubstrings {
		if !strings.Contains(got, want) {
			t.Errorf("generated Odin missing %q", want)
		}
	}

	// Well-formed-looking: the package clause precedes every const declaration.
	pkgIdx := strings.Index(got, "package funpack")
	firstConst := strings.Index(got, "::")
	if pkgIdx < 0 || firstConst < 0 || pkgIdx > firstConst {
		t.Errorf("package clause must precede const declarations (pkg=%d, const=%d)", pkgIdx, firstConst)
	}
}
