// The contract-gen pin gate — the single drift guard that keeps
// funpack/api_contract.gen.odin in lockstep with contract/funpack-api.json: it
// regenerates the Odin source IN MEMORY through the SAME generate_contract_odin
// renderer the committed file was produced by, and byte-compares against the
// #load-embedded committed bytes. A drift — a contract edit without a regen, a
// stale checkout, or a hand-edit of the generated file — fails here, naming the
// fix (`funpack mcp gen-contract` + recommit). There is no second, divergent
// renderer to keep in sync (the gen-core-shared-by-gen-and-pin design the corpus
// pin also follows).
//
// HERMETIC: both inputs are #load-embedded at compile time (the committed contract
// JSON and the committed generated Odin), so this gate needs no source tree on disk
// and runs ALWAYS on the default `odin test .` floor — there is nothing to skip. The
// negative control mutates the embedded contract in memory and asserts the regen
// DIVERGES, proving the byte-compare is content-sensitive (not trivially always-pass).
package main

import "core:strings"
import "core:testing"

// COMMITTED_CONTRACT_JSON is the committed contract/funpack-api.json, #load-embedded
// at compile time (relative to cmd/funpack/). It is the generator INPUT the pin
// regenerates from — the same bytes a `funpack mcp gen-contract` reads off disk.
COMMITTED_CONTRACT_JSON :: #load("../../contract/funpack-api.json", string)

// COMMITTED_CONTRACT_ODIN is the committed funpack/api_contract.gen.odin, #load-
// embedded at compile time. It is the generator OUTPUT the pin compares against — the
// snapshot in the binary the live renderer must reproduce byte-for-byte.
COMMITTED_CONTRACT_ODIN :: #load("../../funpack/api_contract.gen.odin", string)

// test_contract_gen_pin_byte_match is the pin gate proper: it regenerates the Odin
// source through generate_contract_odin against the committed contract bytes and
// asserts byte-equality with the committed funpack/api_contract.gen.odin. A drift
// fails here with the regenerate-and-recommit instruction. This is the forward
// direction — the committed file IS what the live renderer produces.
@(test)
test_contract_gen_pin_byte_match :: proc(t: ^testing.T) {
	regenerated, ok := generate_contract_odin(COMMITTED_CONTRACT_JSON, context.temp_allocator)
	testing.expect(t, ok, "generate_contract_odin failed against the committed contract")
	if !ok {
		return
	}
	testing.expectf(
		t,
		regenerated == COMMITTED_CONTRACT_ODIN,
		"funpack/api_contract.gen.odin drifted from a fresh walk of contract/funpack-api.json; run `funpack mcp gen-contract` and recommit (regenerated %d bytes vs committed %d)",
		len(regenerated),
		len(COMMITTED_CONTRACT_ODIN),
	)
}

// test_contract_gen_mutated_contract_diverges is the negative-control: it proves the
// pin byte-compare actually FIRES on a contract change, so the gate is not trivially
// always-pass. It mutates the embedded contract (renames the first §28 command via a
// targeted string substitution that touches both its declaration and its tool-name
// projection), regenerates, and asserts the output diverges from BOTH the committed
// file and an unmutated regen — the reverse drift direction. It needs only the
// embedded bytes, so it runs ALWAYS.
@(test)
test_contract_gen_mutated_contract_diverges :: proc(t: ^testing.T) {
	baseline, baseline_ok := generate_contract_odin(COMMITTED_CONTRACT_JSON, context.temp_allocator)
	testing.expect(t, baseline_ok, "baseline regen failed")
	if !baseline_ok {
		return
	}

	// Rename the `load` time command to `load_renamed` everywhere it appears in the
	// contract JSON: the command's `"name": "load"` declaration AND any other "load"
	// literal. The generated CMD_LOAD const and the time_load Tool_Spec must shift, so
	// the rendered bytes MUST differ from the committed snapshot.
	mutated_contract, _ := strings.replace_all(
		COMMITTED_CONTRACT_JSON,
		"\"name\": \"load\"",
		"\"name\": \"load_renamed\"",
		context.temp_allocator,
	)
	testing.expect(t, mutated_contract != COMMITTED_CONTRACT_JSON, "mutation did not change the contract bytes")

	mutated, mutated_ok := generate_contract_odin(mutated_contract, context.temp_allocator)
	testing.expect(t, mutated_ok, "generate_contract_odin failed against the mutated contract")
	if !mutated_ok {
		return
	}

	testing.expect(
		t,
		mutated != COMMITTED_CONTRACT_ODIN,
		"a mutated contract regenerated byte-identical output — the pin byte-compare is not content-sensitive",
	)
	testing.expect(
		t,
		mutated != baseline,
		"a mutated contract matched the unmutated regen — the generator ignored the command rename",
	)
}

// test_contract_gen_malformed_contract_refused asserts the generator fails loudly
// (ok=false, no panic) on input that is not a contract object, rather than emitting a
// half-rendered file — the malformed-input contract the §28 codec also holds.
@(test)
test_contract_gen_malformed_contract_refused :: proc(t: ^testing.T) {
	_, array_ok := generate_contract_odin("[1, 2, 3]", context.temp_allocator)
	testing.expect(t, !array_ok, "a JSON array was accepted as a contract")

	_, garbage_ok := generate_contract_odin("not json at all", context.temp_allocator)
	testing.expect(t, !garbage_ok, "non-JSON input was accepted as a contract")

	_, empty_ok := generate_contract_odin("{}", context.temp_allocator)
	testing.expect(t, !empty_ok, "an empty object with no contract_version was accepted")
}
