package main

import "core:strings"
import "core:testing"

COMMITTED_CONTRACT_JSON :: #load("../../contract/funpack-api.json", string)

COMMITTED_CONTRACT_ODIN :: #load("../../funpack/api_contract.gen.odin", string)

@(test)
test_contract_gen_pin_byte_match :: proc(t: ^testing.T) {
	regenerated, ok := generate_contract_odin(COMMITTED_CONTRACT_JSON, context.temp_allocator)
	testing.expect(t, ok, "generate_contract_odin failed against the committed contract")
	if !ok {
		return
	}
	testing.expectf(
		t,
		regenerated == COMMITTED_CONTRACT_ODIN,
		"funpack/api_contract.gen.odin drifted from a fresh walk of contract/funpack-api.json; run `funpack mcp gen-contract` and recommit (regenerated %d bytes vs committed %d)",
		len(regenerated),
		len(COMMITTED_CONTRACT_ODIN),
	)
}

@(test)
test_contract_gen_mutated_contract_diverges :: proc(t: ^testing.T) {
	baseline, baseline_ok := generate_contract_odin(COMMITTED_CONTRACT_JSON, context.temp_allocator)
	testing.expect(t, baseline_ok, "baseline regen failed")
	if !baseline_ok {
		return
	}

	mutated_contract, _ := strings.replace_all(
		COMMITTED_CONTRACT_JSON,
		"\"name\": \"load\"",
		"\"name\": \"load_renamed\"",
		context.temp_allocator,
	)
	testing.expect(t, mutated_contract != COMMITTED_CONTRACT_JSON, "mutation did not change the contract bytes")

	mutated, mutated_ok := generate_contract_odin(mutated_contract, context.temp_allocator)
	testing.expect(t, mutated_ok, "generate_contract_odin failed against the mutated contract")
	if !mutated_ok {
		return
	}

	testing.expect(
		t,
		mutated != COMMITTED_CONTRACT_ODIN,
		"a mutated contract regenerated byte-identical output — the pin byte-compare is not content-sensitive",
	)
	testing.expect(
		t,
		mutated != baseline,
		"a mutated contract matched the unmutated regen — the generator ignored the command rename",
	)
}

@(test)
test_contract_gen_malformed_contract_refused :: proc(t: ^testing.T) {
	_, array_ok := generate_contract_odin("[1, 2, 3]", context.temp_allocator)
	testing.expect(t, !array_ok, "a JSON array was accepted as a contract")

	_, garbage_ok := generate_contract_odin("not json at all", context.temp_allocator)
	testing.expect(t, !garbage_ok, "non-JSON input was accepted as a contract")

	_, empty_ok := generate_contract_odin("{}", context.temp_allocator)
	testing.expect(t, !empty_ok, "an empty object with no contract_version was accepted")
}
