package main

import "core:encoding/json"
import "core:fmt"
import "core:slice"
import "core:strings"

generate_contract_odin :: proc(contract_json: string, allocator := context.allocator) -> (source: string, ok: bool) {
	parsed, parse_err := json.parse(
		transmute([]u8)contract_json,
		json.DEFAULT_SPECIFICATION,
		true,
		context.temp_allocator,
	)
	if parse_err != .None {
		return "", false
	}
	root, is_object := parsed.(json.Object)
	if !is_object {
		return "", false
	}

	b := strings.builder_make(allocator)

	strings.write_string(&b, "// Code generated by `funpack mcp gen-contract`; DO NOT EDIT.\n")
	strings.write_string(&b, "//\n")
	strings.write_string(&b, "// Source of truth: contract/funpack-api.json. Regenerate with the Odin-native\n")
	strings.write_string(&b, "// `funpack mcp gen-contract` verb (cmd/funpack/cli_mcp_gen_contract.odin).\n")
	strings.write_string(&b, "package funpack\n\n")

	contract_version, has_version := contract_int(root, "contract_version")
	if !has_version {
		return "", false
	}
	fmt.sbprintf(&b, "API_CONTRACT_VERSION :: %d\n\n", contract_version)

	version_surface, has_vs := contract_object(root, "version_surface")
	if !has_vs {
		return "", false
	}
	introspect, has_in := contract_object(root, "introspect")
	if !has_in {
		return "", false
	}

	strings.write_string(&b, "// --- `funpack version --json` field names -----------------------------------\n\n")
	fields, _ := contract_object(version_surface, "fields")
	for f in sorted_typed_keys(fields) {
		fmt.sbprintf(&b, "VERSION_FIELD_%s :: %q\n", odin_const(f), f)
	}
	strings.write_string(&b, "\n")

	strings.write_string(&b, "// --- schema names -----------------------------------------------------------\n\n")
	for name in contract_string_array(version_surface, "schema_names") {
		fmt.sbprintf(&b, "SCHEMA_NAME_%s :: %q\n", odin_const(name), name)
	}
	strings.write_string(&b, "\n")

	strings.write_string(&b, "// --- §28 envelope field names -----------------------------------------------\n\n")
	envelopes, _ := contract_object(introspect, "envelopes")
	for kind in ([]string{"request", "response", "event"}) {
		env, has_env := contract_object(envelopes, kind)
		if !has_env {
			continue
		}
		for field in contract_string_array(env, "fields") {
			fmt.sbprintf(&b, "ENVELOPE_%s_FIELD_%s :: %q\n", odin_const(kind), odin_const(field), field)
		}
	}
	strings.write_string(&b, "\n")

	strings.write_string(&b, "// --- §28 command names ------------------------------------------------------\n\n")
	command_groups, _ := contract_object(introspect, "command_groups")
	for g in sorted_typed_keys(command_groups) {
		grp, _ := contract_object(command_groups, g)
		class, _ := contract_string(grp, "class")
		fmt.sbprintf(&b, "// group %q (class %s)\n", g, class)
		for cmd in contract_command_names(grp) {
			fmt.sbprintf(&b, "CMD_%s :: %q\n", odin_const(cmd), cmd)
		}
		strings.write_string(&b, "\n")
	}

	strings.write_string(&b, "// --- §28 event names --------------------------------------------------------\n\n")
	for e in contract_string_array(introspect, "events") {
		fmt.sbprintf(&b, "EVENT_%s :: %q\n", odin_const(e), e)
	}

	strings.write_string(&b, "\n")
	render_tool_specs(&b, introspect, root)

	return strings.to_string(b), true
}

render_tool_specs :: proc(b: ^strings.Builder, introspect: json.Object, root: json.Object) {
	strings.write_string(b, "// --- MCP tools/list projection (Tool_Spec table) ----------------------------\n")
	strings.write_string(b, "//\n")
	strings.write_string(b, "// Generated FROM contract/funpack-api.json: each §28 command_groups command AND\n")
	strings.write_string(b, "// each server_tools tool becomes one MCP tool in the SAME table. A §28 command's\n")
	strings.write_string(b, "// input_schema is the wire `args` shape PLUS the always-present session_id, any\n")
	strings.write_string(b, "// MCP-render-only `mcp_args` the command declares, and (for observe-class\n")
	strings.write_string(b, "// commands) the optional `branch` selector; a server-native\n")
	strings.write_string(b, "// tool's input_schema is its `args` verbatim. tools/list reads TOOL_SPECS;\n")
	strings.write_string(b, "// tools/call dispatches on .command / .group — one source so the advertised\n")
	strings.write_string(b, "// schema cannot drift from dispatch.\n\n")

	strings.write_string(b, "// Tool_Arg is one MCP input_schema property: the JSON name, its JSON-Schema\n")
	strings.write_string(b, "// type, whether it is required, and its description.\n")
	strings.write_string(b, "Tool_Arg :: struct {\n")
	strings.write_string(b, "\tname:      string,\n")
	strings.write_string(b, "\tjson_type: string,\n")
	strings.write_string(b, "\trequired:  bool,\n")
	strings.write_string(b, "\tdoc:       string,\n")
	strings.write_string(b, "}\n\n")

	strings.write_string(b, "// Tool_Spec is one MCP tool: its advertised tool name and full input_schema\n")
	strings.write_string(b, "// (args), plus the dispatch hints tools/call switches on (the wire command, its\n")
	strings.write_string(b, "// declaring group/family, and the determinism class). It carries BOTH classes of\n")
	strings.write_string(b, "// MCP tool from one table: a §28 session command (session_scoped = true, group is\n")
	strings.write_string(b, "// its §28 group, command is the wire command) and a server-native tool\n")
	strings.write_string(b, "// (session_scoped = false, group is its dispatch family, command equals the tool\n")
	strings.write_string(b, "// name — no §28 wire command exists). One unified table is the whole point: every\n")
	strings.write_string(b, "// tool tools/list advertises and tools/call dispatches reads from here.\n")
	strings.write_string(b, "Tool_Spec :: struct {\n")
	strings.write_string(b, "\tname:           string,\n")
	strings.write_string(b, "\tcommand:        string,\n")
	strings.write_string(b, "\tgroup:          string,\n")
	strings.write_string(b, "\tclass:          string,\n")
	strings.write_string(b, "\tsession_scoped: bool,\n")
	strings.write_string(b, "\targs:           []Tool_Arg,\n")
	strings.write_string(b, "}\n\n")

	strings.write_string(b, "// SESSION_ID_ARG is the universal session selector every §28 tool carries — the\n")
	strings.write_string(b, "// MCP handle that keys the live debug session a tools/call dispatches into.\n")
	strings.write_string(b, "SESSION_ID_ARG :: Tool_Arg{\n")
	strings.write_string(b, "\tname      = \"session_id\",\n")
	strings.write_string(b, "\tjson_type = \"string\",\n")
	strings.write_string(b, "\trequired  = true,\n")
	strings.write_string(b, "\tdoc       = \"opaque id of the live session, as returned by session_start\",\n")
	strings.write_string(b, "}\n\n")

	strings.write_string(b, "// BRANCH_ARG is the optional §28 observe-addressing selector every observe-class\n")
	strings.write_string(b, "// tool carries: omitted reads the canonical timeline, set reads a checkout-\n")
	strings.write_string(b, "// created branch.\n")
	strings.write_string(b, "BRANCH_ARG :: Tool_Arg{\n")
	strings.write_string(b, "\tname      = \"branch\",\n")
	strings.write_string(b, "\tjson_type = \"string\",\n")
	strings.write_string(b, "\trequired  = false,\n")
	strings.write_string(b, "\tdoc       = \"optional §28 observe-addressing selector: omit for the canonical timeline, set to a checkout-created branch name\",\n")
	strings.write_string(b, "}\n\n")

	strings.write_string(b, "// TOOL_SPECS is the generated tools/list projection: the FULL MCP tool surface\n")
	strings.write_string(b, "// in one table — the §28 commands first (groups sorted, commands as declared),\n")
	strings.write_string(b, "// then the server-native tools (families sorted, tools as declared). Both\n")
	strings.write_string(b, "// sections are projected from contract/funpack-api.json by the same walk, so the\n")
	strings.write_string(b, "// advertised input_schema cannot drift from dispatch. A package-level `:=` (not\n")
	strings.write_string(b, "// `::`) because an Odin slice literal is not a compile-time constant; it is\n")
	strings.write_string(b, "// read-only by convention (a generated table tools/list walks, never mutates).\n")
	strings.write_string(b, "TOOL_SPECS := []Tool_Spec{\n")

	command_groups, _ := contract_object(introspect, "command_groups")
	for g in sorted_typed_keys(command_groups) {
		grp, _ := contract_object(command_groups, g)
		class, _ := contract_string(grp, "class")
		tool_prefix, _ := contract_string(grp, "tool_prefix")
		commands, _ := contract_array(grp, "commands")
		for command_value in commands {
			command, command_ok := command_value.(json.Object)
			if !command_ok {
				continue
			}
			name, _ := contract_string(command, "name")
			strings.write_string(b, "\t{\n")
			fmt.sbprintf(b, "\t\tname           = %q,\n", contract_tool_name(tool_prefix, name))
			fmt.sbprintf(b, "\t\tcommand        = %q,\n", name)
			fmt.sbprintf(b, "\t\tgroup          = %q,\n", g)
			fmt.sbprintf(b, "\t\tclass          = %q,\n", class)
			strings.write_string(b, "\t\tsession_scoped = true,\n")
			strings.write_string(b, "\t\targs           = []Tool_Arg{\n")
			strings.write_string(b, "\t\t\tSESSION_ID_ARG,\n")
			args, _ := contract_object(command, "args")
			render_arg_entries(b, args)
			if mcp_args, has_mcp := contract_object(command, "mcp_args"); has_mcp {
				render_arg_entries(b, mcp_args)
			}
			if class == "observe" {
				strings.write_string(b, "\t\t\tBRANCH_ARG,\n")
			}
			strings.write_string(b, "\t\t},\n")
			strings.write_string(b, "\t},\n")
		}
	}

	render_server_tool_specs(b, root)
	strings.write_string(b, "}\n")
}

render_server_tool_specs :: proc(b: ^strings.Builder, root: json.Object) {
	server_tools, has_st := contract_object(root, "server_tools")
	if !has_st {
		return
	}
	families, has_fam := contract_object(server_tools, "families")
	if !has_fam {
		return
	}
	for fam_name in sorted_typed_keys(families) {
		fam, _ := contract_object(families, fam_name)
		class, _ := contract_string(fam, "class")
		session_scoped, _ := contract_bool(fam, "session_scoped")
		tools, _ := contract_array(fam, "tools")
		for tool_value in tools {
			tool, tool_ok := tool_value.(json.Object)
			if !tool_ok {
				continue
			}
			name, _ := contract_string(tool, "name")
			strings.write_string(b, "\t{\n")
			fmt.sbprintf(b, "\t\tname           = %q,\n", name)
			fmt.sbprintf(b, "\t\tcommand        = %q,\n", name)
			fmt.sbprintf(b, "\t\tgroup          = %q,\n", fam_name)
			fmt.sbprintf(b, "\t\tclass          = %q,\n", class)
			fmt.sbprintf(b, "\t\tsession_scoped = %t,\n", session_scoped)
			strings.write_string(b, "\t\targs           = []Tool_Arg{\n")
			args, _ := contract_object(tool, "args")
			render_arg_entries(b, args)
			strings.write_string(b, "\t\t},\n")
			strings.write_string(b, "\t},\n")
		}
	}
}

render_arg_entries :: proc(b: ^strings.Builder, args: json.Object) {
	for arg_name in sorted_typed_keys(args) {
		arg, arg_ok := args[arg_name].(json.Object)
		if !arg_ok {
			continue
		}
		arg_type, _ := contract_string(arg, "type")
		required, _ := contract_bool(arg, "required")
		doc, _ := contract_string(arg, "doc")
		strings.write_string(b, "\t\t\t{")
		fmt.sbprintf(b, "name = %q, ", arg_name)
		fmt.sbprintf(b, "json_type = %q, ", arg_type)
		fmt.sbprintf(b, "required = %t, ", required)
		fmt.sbprintf(b, "doc = %s", odin_string(doc))
		strings.write_string(b, "},\n")
	}
}

odin_const :: proc(name: string, allocator := context.allocator) -> string {
	return strings.to_upper(name, allocator)
}

odin_string :: proc(s: string, allocator := context.allocator) -> string {
	b := strings.builder_make(allocator)
	strings.write_byte(&b, '"')
	for i in 0 ..< len(s) {
		switch s[i] {
		case '\\':
			strings.write_string(&b, "\\\\")
		case '"':
			strings.write_string(&b, "\\\"")
		case '\n':
			strings.write_string(&b, "\\n")
		case '\t':
			strings.write_string(&b, "\\t")
		case:
			strings.write_byte(&b, s[i])
		}
	}
	strings.write_byte(&b, '"')
	return strings.to_string(b)
}

contract_tool_name :: proc(tool_prefix, command: string, allocator := context.allocator) -> string {
	if tool_prefix == "" {
		return strings.clone(command, allocator)
	}
	return strings.concatenate({tool_prefix, "_", command}, allocator)
}

sorted_typed_keys :: proc(object: json.Object, allocator := context.allocator) -> []string {
	keys := make([dynamic]string, 0, len(object), allocator)
	for k in object {
		if k == "$comment" {
			continue
		}
		append(&keys, k)
	}
	slice.sort(keys[:])
	return keys[:]
}

contract_command_names :: proc(grp: json.Object, allocator := context.allocator) -> []string {
	commands, _ := contract_array(grp, "commands")
	names := make([dynamic]string, 0, len(commands), allocator)
	for command_value in commands {
		command, ok := command_value.(json.Object)
		if !ok {
			continue
		}
		if name, has := contract_string(command, "name"); has {
			append(&names, name)
		}
	}
	return names[:]
}

contract_object :: proc(object: json.Object, key: string) -> (value: json.Object, has: bool) {
	field, present := object[key]
	if !present {
		return {}, false
	}
	return field.(json.Object)
}

contract_array :: proc(object: json.Object, key: string) -> (value: json.Array, has: bool) {
	field, present := object[key]
	if !present {
		return {}, false
	}
	return field.(json.Array)
}

contract_string :: proc(object: json.Object, key: string) -> (value: string, has: bool) {
	field, present := object[key]
	if !present {
		return "", false
	}
	str, is_string := field.(json.String)
	if !is_string {
		return "", false
	}
	return string(str), true
}

contract_bool :: proc(object: json.Object, key: string) -> (value: bool, has: bool) {
	field, present := object[key]
	if !present {
		return false, false
	}
	b, is_bool := field.(json.Boolean)
	if !is_bool {
		return false, false
	}
	return bool(b), true
}

contract_int :: proc(object: json.Object, key: string) -> (value: i64, has: bool) {
	field, present := object[key]
	if !present {
		return 0, false
	}
	#partial switch v in field {
	case json.Integer:
		return i64(v), true
	case json.Float:
		return i64(v), true
	}
	return 0, false
}

contract_string_array :: proc(object: json.Object, key: string, allocator := context.allocator) -> []string {
	arr, has := contract_array(object, key)
	if !has {
		return {}
	}
	out := make([dynamic]string, 0, len(arr), allocator)
	for element in arr {
		if str, ok := element.(json.String); ok {
			append(&out, string(str))
		}
	}
	return out[:]
}
